version: "3.3"

services:
  tb_bimonthly_frontend_prod:
    image: tb_bimonthly_frontend_prod
    container_name: tb_bimonthly_frontend_prod
    restart: always
    build:
      context: .
      args:
        - VITE_BASE=/tb-bimonthly/
        - VITE_BACKEND_URL=https://swc.iitg.ac.in/tb-bimonthly/api
    ports:
      - "5672:3000"
    env_file:
      - .env
    networks:
      - tb_bimonthly_network

networks:
  tb_bimonthly_network:
    external: true
