version: "3.3"

services:
  tb_bimonthly_backend_prod:
    image: tb_bimonthly_backend_prod
    container_name: tb_bimonthly_backend_prod
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - tb_bimonthly_uploads_prod:/app/uploads

    ports:
      - "5673:5000"
    env_file:
      - .env
    networks:
      - tb_bimonthly_network

volumes:
  tb_bimonthly_uploads_prod:

networks:
  tb_bimonthly_network:
    external: true
